### ISSUE TITLE
Remove AWS_ACCESS_KEY env vars from everywhere

### ISSUE THREAD

**Issue by jfromaniello** [auth0/auth0-instrumentation#1]
Remove these two env vars `AWS_ACCESS_KEY_SECRET` and `AWS_ACCESS_KEY_ID` from everywhere since this is not needed when using the AWS sdk properly.

The SDK can take this from either process.env, role, etc.

**Comment by elbuo8** [comment]
@dirceu this is done right?

**Comment by dirceu** [comment]
Yes 👍
