### ISSUE TITLE
consider passing parameters instead of ENV like any other node.js module

### ISSUE THREAD

**Issue by jfromaniello** [auth0/auth0-instrumentation#2]
I like clear interfaces, `env` or `process.env` is too much information. Consider using a params like object with camel cased settings as any other node.js module.

We have had problems in the past on modules that receive env like auth0/ext, tenant-audit etc. That code is hard to read, think and the interfaces are not clear.

**Comment by jfryman** [comment]
@jfromaniello are you familiar with the 12-factor app? Specifically, take a look at http://12factor.net/config

http://12factor.net/

It is highly probable that in the future, code is just going to run on resources that we allocate, with scheduling and configuration being set via an environment variable.

If this is not intuitive now, I think there are ways we can reduce this pain by introducing some pre-populated ENV vars on systems while we figure out the long term strategy, but by and large this is how we'll be able to abstract the application needing to be tightly coupled to a configuration management tool or config file.

Thoughts?

**Comment by jfromaniello** [comment]
@jfryman I am familiar with 12factor, I really like that. 

The problem I have is that this is a library, not an app, intended to be used from applications.

A library should not read env vars directly, but instead accept parameters with a clear interface.

**Comment by jfryman** [comment]
The library runs in the context of the app, no? I don't see the difference.

**Comment by jfryman** [comment]
I will say this, though. Until the time where "we" (hal/brukker) can provide these environment variables for you, for free, as part of the execution environment, expecting it to be passed in as an ENV can be, it could be very much obnoxious. It's another config point that the developer needs to know of the system at large in order to run an app using this library.

What I want to say though is that is there a better way we can expose the interface but have it read from ENV by default? I think that's the goal here, maybe it's just a matter of renaming the config override?

**Comment by dirceu** [comment]
We can have an intermediate step that transforms things like `env.ERROR_REPORTING_URL` to, say, `config.error_reporting.url`; that will certainly improve readability.

However, using env vars can facilitate the adoption of this tool by internal projects that already have those configured (so... almost all of them).

**Comment by jfromaniello** [comment]
The problems I have with internal libs receiving `env` is more with code practices than with deployments itself:

1.  Sometimes is not properly documented what variables the lib expect eg: https://github.com/auth0/auth0-tenant-audit , https://github.com/auth0/auth0-ext . It is not the case of this library which has a clear example on the README.
2.  Sometimes we initialise from the caller code like this `lib.init({env: env})`, it is not clear from the caller what does the library needs from env.
3.  If we want to make 2 clear, like `{env: { FOO: env.FOO, BAR: env.BAR}}` then it doesn't feel natural. It is a weird way to initialise something, different to 99.99% of the libraries on npm.
4. It makes the library weird if you need to pass parameter which is not in the ENVs eg: https://github.com/auth0/auth0-tenant-audit/blob/master/lib/logs.js#L24-L35 is like "I need all these things and BTW I also need all your env vars". 
5.  It might hide that a single class needs too much things to start up. Like a [God object](https://en.wikipedia.org/wiki/God_object)
6.  It usually makes me search inside the library where and how is env being used because of the lack of a clear interface.

**Comment by dirceu** [comment]
Fair enough, I agree @jfromaniello. This will just change the API @jfryman: we'll still pass the values found in the env vars, but in a clearer, more explicit way.

We can do this improvement in other iterations.

**Comment by elbuo8** [comment]
@dirceu this is done right?
