### ISSUE TITLE
Improve logging performance

### ISSUE THREAD

**Issue by dirceu** [auth0/auth0-instrumentation#44]
We should benchmark the use of all these multiple logging streams at the same time, since this [is known to be a resource hog](https://github.com/pinojs/pino-multi-stream#caveats).

I did some initial testing with [pino](https://github.com/pinojs/pino) and it seems promising (although didn't collect numbers in a controlled manner, etc). There are a few caveats:

- The data changes _slightly_: we don't send `ProcessInfo` or `pkg.name` anymore.
- No Sentry support (not out-of-the-box with an npm package, at least).
- No serializer support: from what I've seen, this is the only deal breaker. If we can implement it, we're good.

The pino version can be found [here](https://gist.github.com/dirceu/6da35b1aab28150c9b5086e9e1a7bb6a).

**Comment by elbuo8** [comment]
This is where fluentd would come in <3

We just log to stdout with pino and have fluentd send to sentry, kibana, and whatever else we want.

**Comment by Neirda24** [comment]
@elbuo8 : Is there a way to send logs to FluentD ?
