### ISSUE TITLE
Design and implement rate limiting for sending logs

### ISSUE THREAD

**Issue by hazen** [auth0/auth0-instrumentation#66]
Related to this discussion https://auth0.slack.com/archives/C6TSSQD0U/p1507064265000103

Yenkel is suggesting using https://www.npmjs.com/package/debounce 

From Verlic:
> We do not want to waste time in limitd and debounce must be correct, e.g. if we have 25 exceptions in a second and they are all different is ok.  but…. if the exception A is “different” than exception B just because the tenant name changed, then that should be “debounced”. We only need 1 exception.  For these we need to understand the scenarios that happened in the past few weeks that greatly increase the usage of Sentry (#sentry_plan_changes )

Replaces https://github.com/auth0/dx/issues/197

**Comment by half-ogre** [comment]
Sentry already has it's own logic to collapse repeated errors, so I'm not sure this is the right direction. If we were to debounce, I would expect limitd to do it; the cost shouldn't be very high, but we'd need to benchmark it. Ideally, the logging layer shouldn't have these smarts.
