### ISSUE TITLE
Improve tagging in auth0-instrumentation

### ISSUE THREAD

**Issue by hazen** [auth0/auth0-instrumentation#68]
Related to https://auth0.slack.com/archives/C04SSNEKT/p1507125019000044

 **jose [Today at 7:50 AM]** 
in *#logs_uncaught*
> so [@U45GBFLKZ](https://github.com/half-ogre), sentry is properly logging uncaugh exceptions but as you mention maybe we can do a better job tagging:
https://github.com/auth0/auth0-server/blob/f2b455007901ec0e13cadfda385a2de6b6b1eb2e/lib/logs/logger.js#L6
https://github.com/auth0/auth0-instrumentation/blob/master/lib/logger.js#L69-L74

2 replies
**half-ogre [5 hours ago]**
> Yeah, the tagging is the issue. Otherwise I can't send just the uncaughts to PD.

**half-ogre [5 hours ago]**
> I haven't found a good extensibility point in Raven for this. I am thinking about making a custom stream that dynamically sets the error level and pushes the tags.

Replaces https://github.com/auth0/dx/issues/198

**Comment by half-ogre** [comment]
Fixed by #69
