### ISSUE TITLE
Switch back to v8-profiler once it supports NodeJS version 8.x

### ISSUE THREAD

**Issue by hazen** [auth0/auth0-instrumentation#74]
A change was made in https://github.com/auth0/auth0-instrumentation/pull/65 to support Node version 8.x.  It was a forked version of the standard v8-profiler which had been modified to support Node 8.

So it looks like hyj1991 created his own fork and applied a patch to create the new NPM release. node-inspector/v8-profiler#113

Once this gets merged back to the base and there is a mainline version supporting Node 8, we will probably want to switch this dep back to https://www.npmjs.com/package/v8-profiler.

**Comment by nw** [comment]
`v8-profiler` hasn't been updated in 3 years. Sticking with `v8-profiler-next`
