### ISSUE TITLE
conventions, usage

### ISSUE THREAD

**Issue by boneskull** [auth0/auth0-instrumentation#8]
- In a Hapi context, `init()` is a bit of a problem.  A consumer must call `agent.init()` before any plugins actually become available to register, which is contrary to common Hapi plugin conventions.
  - Furthermore, calling `init()` doesn't allow _a la carte_ usage; it'll try to init logging, error reporting, and metrics at once.
  - `init()` also attempts to make `agent` a singleton (though makes no such guarantees).  This can make more "granular" usage difficult, if not impossible.  Is this necessary?
- ~~By expecting `package.json`, this module's functionality is tightly coupled to a Node.js context.~~  Is this necessary?

Some ideas:
- initialize things when the Hapi plugin's "register" function is called; not before
- each chunk of functionality should allow explicit initialization--whether this is three (3) separate function calls, or a single function call with appropriate options
- extract the Hapi plugin (and Express middleware for that matter) into their own modules
- expect a _single_ configuration object, not `pkg` and `env`
- return a new object every time `init()` (or whatever) is called.  If this is implemented, don't make consumers use `new`

**UPDATE**: This module doesn't expect a `package.json`; just rather something that looks like it.

**Comment by jfromaniello** [comment]
ok

**Comment by boneskull** [comment]
@jfromaniello does that mean you are in complete agreement with all my points? 😄
