### ISSUE TITLE
Add Snyk Support

### ISSUE THREAD

**Issue by hazen** [auth0/auth0-instrumentation#85]
Currently three errors have been flagged in the `customer API` repo caused by insecure dependencies. Namely:
* `string` in [swagger-tools](https://snyk.io/test/npm/swagger-tools/0.10.3)
* [debug](https://snyk.io/test/npm/debug)
* [moment](https://snyk.io/test/npm/moment)
* [ms](https://snyk.io/test/npm/ms)

**Comment by nw** [comment]
done
